# Site

title: COVID Vaccination Watch Docs
description: Docs for the wrapped COVID vaccination data API
url: servicestackapps.github.io/CovidVaccinationWatch/
repository: ServiceStackApps/CovidVaccinationWatch
google_analytics_key:
baseurl: /CovidVaccinationWatch

collections:
  documentation:
    title: Documentation
    output: true
    permalink: /:slug.html
plugins:
  - github-pages

exclude:
  - README.md
  - LICENCE

topics: []
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      collection: documentation
    values:
      priority: 999
  -
    scope:
      collection: releases
    values:
      layout: default

# -----
# Build
sass:
  sass_dir: _scss
  style: :compressed